Android-Team-13-Maniacs/android_project_maniacs

- app/src/main/java/com/example/android_teammaniacs_project/data/Reply.kt
- app/src/main/java/com/example/android_teammaniacs_project/data/Video.kt
- app/src/main/res/layout/video_item.xml
- app/src/main/res/values/strings.xml
> VideoItem layout 구현

- app/src/main/java/com/example/android_teammaniacs_project/main/MainViewPagerAdapter.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchAdapter.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
[FEAT] : ⚙️ Search RecyclerView Adapter 구현
> [FEAT] : ⚙️ Search RecyclerView Adapter 구현

- app/src/main/res/drawable/add_selector.xml
- app/src/main/res/drawable/like_selector.xml
>  [DESIGN] : 🎨 | 각 버튼 커스텀 하기(2)

- app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeBannerAdapter.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeVideoAdapter.kt
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/layout/home_banner_item.xml
- Home Fragment 어댑터, 프레그먼트를 수정 하였습니다.
- Home Fragment 에서 item click 구현 완료 하였습니다.
> [FEAT] : ⚙️ Home Itme Click

- app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
> [FEAT] : ⚙️ | 각 버튼 클릭시 토스트 메세지 추가하기

- .gitignore
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/android_teammaniacs_project/constants/Constants.kt
- app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/PopularVideoModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitClient.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/SearchVideoModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchAdapter.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModelFactory.kt
[FEAT] : ⚙️ SearchFragment 검색 기능 구현
> [FEAT] : ⚙️ SearchFragment 검색 기능 구현

- app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
- app/src/main/res/layout/fragment_search.xml
[DESIGN] : 🎨SearchFragment UI 수정
>  [DESIGN] : 🎨SearchFragment UI 수정

- app/src/main/java/com/example/android_teammaniacs_project/constants/SearchButtonType.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
- app/src/main/res/layout/fragment_search.xml
선택 기준 별 Search 기능 구현 / Button Type enum class 추가
> [FEAT] : ⚙️ 선택 기준 별 Search 기능 구현

- app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
[FEAT] : ⚙️ | DetailActivity에서 값 보여주기 완료했습니다
>  [FEAT] : ⚙️ | DetailActivity에서 값 보여주기

- app/build.gradle
- app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
- app/src/main/res/layout/home_spinner_item.xml
[Feature]: HomeFragment Spinner 구현
> [Feature]: HomeFragment Spinner 구현

- app/src/main/java/com/example/android_teammaniacs_project/constants/Constants.kt
- app/src/main/java/com/example/android_teammaniacs_project/constants/SearchButtonType.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/CategoryModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/PopularVideoModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitClient.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/SearchVideoModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
> [DOCS] : 📚 Retrofit 관련 주석 추가

- app/src/main/java/com/example/android_teammaniacs_project/main/MainActivity.kt
- 아이템 슬라이드시  프래그먼트 슬라이드가 안되도록 수정
> [FIX] : 🔧 viewpager slide

- app/build.gradle
- app/src/main/java/com/example/android_teammaniacs_project/constants/Constants.kt
- app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
- app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoAdapter.kt
- app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoViewModel.kt
> [FEAT] : ⚙️ | My list 추가 기능

- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/CategoryModel.kt
[FEAT] : ⚙️ Category 별 영상 기능 상단 구현
> [FEAT] : ⚙️ Category 별 영상 기능 상단 구현

- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
- app/src/main/res/layout/fragment_home.xml
[FEAT] : ⚙️ HomeFragment 아래 Spinner 구현
> [FEAT] : ⚙️ HomeFragment 아래 Spinner 구현

- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
Category 분할 / Upper Below Category Video 구분
> [FIX] : 🔧 HomeFragment 수정

- app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
>  [FIX] : 🔧 | 공유하기 기능 수정

- app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
- Infinite Scroll 함수 중복 호출 문제 수정
> Infinite Scroll 기능 수정

- app/build.gradle
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/SnapPagerScrollListener.kt
- app/src/main/res/layout/fragment_home.xml
홈 배너에 인디케이터를 부착하여 자동으로 넘어가고, 몇번째 순서인지 알 수 있도록 구현함
> [FEAT] : ⚙️ banner indecator

- app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/NoResultsException.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
> [Feature]: SearchFragment 오류 및 예외 처리

- app/src/main/res/layout/fragment_home.xml
> [FIX] : 🔧  home banner 인디케이터 위치 수정

- app/build.gradle
- app/src/main/java/com/example/android_teammaniacs_project/data/Video.kt
- app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/utils/Utils.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/video_detail_activity.xml
- Detail Fragment 디자인 수정 및 데이터 연동
- Home Fragment popular list size 변경
> Detail Fragment 수정

- app/src/main/java/com/example/android_teammaniacs_project/constants/GoogleKey.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/NoResultsException.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchAdapter.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
- ListAdapter로 수정 
- SearchFragment 리팩토링
> SearchFragment Refactoring

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/android_teammaniacs_project/data/Channel.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeChannelAdapter.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/retrofit/RetrofitInterface.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/values/strings.xml
- 카테고리 별 채널 기능 구현
- HomeFragment 일부 내용 Refactor
> Home Fragment 카테고리 별 채널 기능 추가

- app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailActivity.kt
- app/src/main/java/com/example/android_teammaniacs_project/detail/VideoDetailViewModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/home/HomeViewModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/myVideoPage/MyVideoViewModel.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchFragment.kt
- app/src/main/java/com/example/android_teammaniacs_project/search/SearchViewModel.kt
- HomeFragment / SearchFragment / DetailFragment Nullpoint 예외처리
> [FEAT] : ⚙️ Nullpoint Exception 예외처리
